### ISSUE TITLE
Stage 1 - Send Report

### ISSUE THREAD

**Issue by MarlenAw** [FACN3/easyRep#12]
As a user I want to: 

Click on the Report button that's on the landing page which takes me to a multi page form where I can choose one from various options of hazards and then choose what I feel is related to this hazard, location and the ability to upload a media. 

So that:

I can easily send a report anonymously to the right authorities.

Acceptance criteria: 

- [x] Landing page with obvious Report button #1 
- [x] Multi page form for category, description, location. #3 #2 #13 #14
- [x] Upload media functionality included in the form. #15
- [x] Getting authority contact from the database. #14
- [x] Email template to be filled with the details from the form #16 
- [x] Email sending functionality #17
- [x] A thank you page once the report is submitted  #18
- [x] Setting up config file for production and development #25

Stretch Goals:

- [ ] Click tracking functionality 
- [x] Saving each report in the database and preparation for Stage 2.
